### ISSUE TITLE
See multiple client cursor

### ISSUE THREAD

**Issue by skrilax91** [zuev93/oni_multiplayer#35] opened 2023-03-28 20:57 UTC
I can see my friend's cursor 2 times, one real and another one reversed

**Comment by tinetik** [comment] 2023-03-29 00:11
+1
When the real cursor is bottom right another cursor is mirrored over the origin of my screen to the top right, upside-down.

**Comment by zuev93** [comment] 2023-03-29 06:27
Thanks for you findings, however this ticket is a 
Duplicate of #25

**Closed by zuev93** 2023-03-29 06:27 UTC
