### ISSUE TITLE
Player spawning not showing on either client.

### ISSUE THREAD

**Issue by Antonio0447** [zuev93/oni_multiplayer#100] opened 2023-06-09 20:05 UTC
When you spawn a player on host or whatever you call them it will not show on the client same for client if you spawn a player it will not show for host.

**Comment by zuev93** [comment] 2023-06-09 21:42
Do you refer to bioprinter (teleport)? if so it is duplicate of #30

**Comment by Antonio0447** [comment] 2023-06-09 21:44
> Do you refer to bioprinter (teleport)? if so it is duplicate of #30 

Yes sorry about that I didn’t see #30.

**Closed** 2023-06-09 22:22 UTC
